name: .NET Build and Test (Cart)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test Cart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/cart/Cart.sln

      - name: Build
        run: dotnet build src/cart/Cart.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/cart/Cart.UnitTests/Cart.UnitTests.csproj --configuration Release --no-build --verbosity minimal
